extends: airbnb
env:
  browser: true
  es6: true
  node: true
  mocha: true
rules:
  no-console: 0
  import/extensions: 0
  global-require: 0
  react/no-array-index-key: 1
  react/jsx-no-bind: 1
  jsx-a11y/href-no-hash: 0